sudo: required
language: minimal
services:
- docker
script: "./ci/publish_docker.sh"
branches:
  except:
  - gh-pages
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: SOqoRz63z21Cv4c6J9dH0r8G1FOR6scMVTHUjm5d6gHG16C0O5b/iXDs7qX5nYAGmEQpToYMbSmOAussIm0oifWulYp+H6wIYpf8KhN42qnWoFYOFDfqGTkNIzSXXZJMVNv3gZMTR6DhREJvstVaQkBSi3nzxhKDI/bVDkO/4OlkKOCvHA+MVis1WNZzcBvZ3QWEVuI5t49HhQ0v/MrzqKGwMAzaxkYWXhBowvwS/RJ51Dm5U8rbWafsBnoEvb+uFTm9Bu1CEgT7ZWDBrxoHlbJHyMF6SE3HQlGF/w3s7M5EE6nYedj6GHVq/z6h9mHLhFVNrli/yr/G1tdlxMhgRCgpNs5+TvFXbeswG3nKv3E1GY8P0060YtRWYZ+aQn8Otb8fXEMOy5FqllXRUnsp/kcPhq25kre48imGy+xUDHtJxxqdcXvtHbsawE3n6vAeJ3ZI9gPEC5HYex57PioGT9Db4NKltCP0Y/Skh66+5+EnpJkWY/eTfeB2h7PoZFAsSXbgP/qMG5aaBp1s/wN2UVvnl6MwmwCG8O/BicZpjgn5Ar/fcadAbpYCFffI2KGUSVcbQo5Wabi7LWKUHCIzSyw6FO/j95F89d15ugYFiA6XgcNqrps4PRurWA3uPdcyYBRQFDMZpQOjPizfY9EjsxBVOwd/y3K6lCWAiZc2FCc=
  - secure: Gn2MWDl3MaNgm/rZEsJ/SJZn/d9pxCkWD1hgmCesMt/zKHGYM1YaWhhZXanZtJoxHV1mKAFFNhnKmrPNijCu+weAbi0tID6+JRa7TdOUtA0jIM4njWfOmNddReWHzs4FkwtbGlbx6YUYjaCnMacowIARaaX4g86FlTuFgVCnsnINK6w5p0kXTuQSDDbK5Fo6lxVNTNz9mwXWiBbpit395zrpBGH71EJgXB1qbQPaoyoEp1vntDxLr8cc7qAQ5cmhx6GuEgi63yoXxnCCIjwFdbTHYNQVguTCQmoPs6H3nbwPjPirBGmJ5I4E/K+xlgHcKCpD/z6Fn1fWcrPn9RdkC0HgXlZTBUaC0A1TvTxaZSOorEmUAInbbfJc3Xw2ykNW4/5GcRV+iFYE1cHv8/cNwvYggpLVGcSN1qwFcNyqq3T+XegpdKWXdML+8dAQ7OgXOnmfgXIS8hOGZrYb2MBl+8Zpkq2jDs7wGgtAqpcjhgeOIPnaqaJXm7U7LXe3FRZV4+WGP5ZRauiXe8XxQO1QwiNo3utP5gKERAf4rQgOScMStNy/3v5yVnvnBgKMT6wI9PqvOJ+DUNQ+GAEg/wld+55PW1mX8jjLYo6B1CiFiO+6t/ytJhgy41yBPaOVrvmgdaGCHbwI5rSt32oHxn+jdxydqVK5rRk34gqOTMq+KU4=
